/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package multicolas.retroalimentadas;

/**
 *
 * @author luisy
 */
public class Frame extends javax.swing.JFrame {

    /**
     * Creates new form Frame
     */
    int semaforo = 0;

    boolean ejecutando = false;
    HiloMulticola round;
    HiloMulticola fifo;
    HiloMulticola sjf;

    public Frame(HiloMulticola round, HiloMulticola fifo, HiloMulticola sjf) {
        initComponents();
        //this.txtQuantum.setVisible(false);
        //this.jLabel3.setVisible(false);
        this.round = round;
        this.fifo = fifo;
        this.sjf = sjf;
        
        this.round.setPanel(this.panelround, this.panelsemafororobin);
        this.fifo.setPanel(this.panelfifo, this.panelsemaforofifo);
        this.sjf.setPanel(this.panelsjf, this.panelsemaforosjf);
        
    }

    private Frame() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelsemafororobin2 = new javax.swing.JPanel();
        txtRafaga = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtLLegada = new javax.swing.JTextField();
        cmbAlgoritmo = new javax.swing.JComboBox<>();
        btnIngresar = new javax.swing.JButton();
        btnSimular = new javax.swing.JButton();
        panelRound = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArearobin = new javax.swing.JTextArea();
        panelround = new javax.swing.JPanel();
        panelFIFO = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreafifo = new javax.swing.JTextArea();
        panelfifo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAreasjf = new javax.swing.JTextArea();
        panelsjf = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        panelsemafororobin = new javax.swing.JPanel();
        panelsemaforofifo = new javax.swing.JPanel();
        panelsemaforosjf = new javax.swing.JPanel();

        javax.swing.GroupLayout panelsemafororobin2Layout = new javax.swing.GroupLayout(panelsemafororobin2);
        panelsemafororobin2.setLayout(panelsemafororobin2Layout);
        panelsemafororobin2Layout.setHorizontalGroup(
            panelsemafororobin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 27, Short.MAX_VALUE)
        );
        panelsemafororobin2Layout.setVerticalGroup(
            panelsemafororobin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ráfaga");

        jLabel2.setText("Llegada");

        cmbAlgoritmo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1. Round Robin", "2. FIFO", "3. SJF" }));
        cmbAlgoritmo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAlgoritmoActionPerformed(evt);
            }
        });

        btnIngresar.setLabel("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        btnSimular.setLabel("Simular");
        btnSimular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimularActionPerformed(evt);
            }
        });

        txtArearobin.setColumns(20);
        txtArearobin.setRows(5);
        jScrollPane1.setViewportView(txtArearobin);

        panelround.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout panelroundLayout = new javax.swing.GroupLayout(panelround);
        panelround.setLayout(panelroundLayout);
        panelroundLayout.setHorizontalGroup(
            panelroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 438, Short.MAX_VALUE)
        );
        panelroundLayout.setVerticalGroup(
            panelroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelRoundLayout = new javax.swing.GroupLayout(panelRound);
        panelRound.setLayout(panelRoundLayout);
        panelRoundLayout.setHorizontalGroup(
            panelRoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRoundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelround, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        panelRoundLayout.setVerticalGroup(
            panelRoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRoundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE))
                .addContainerGap())
        );

        txtAreafifo.setColumns(20);
        txtAreafifo.setRows(5);
        jScrollPane2.setViewportView(txtAreafifo);

        panelfifo.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout panelfifoLayout = new javax.swing.GroupLayout(panelfifo);
        panelfifo.setLayout(panelfifoLayout);
        panelfifoLayout.setHorizontalGroup(
            panelfifoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelfifoLayout.setVerticalGroup(
            panelfifoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelFIFOLayout = new javax.swing.GroupLayout(panelFIFO);
        panelFIFO.setLayout(panelFIFOLayout);
        panelFIFOLayout.setHorizontalGroup(
            panelFIFOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFIFOLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelfifo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelFIFOLayout.setVerticalGroup(
            panelFIFOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFIFOLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFIFOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelfifo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE))
                .addContainerGap())
        );

        txtAreasjf.setColumns(20);
        txtAreasjf.setRows(5);
        jScrollPane3.setViewportView(txtAreasjf);

        panelsjf.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout panelsjfLayout = new javax.swing.GroupLayout(panelsjf);
        panelsjf.setLayout(panelsjfLayout);
        panelsjfLayout.setHorizontalGroup(
            panelsjfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelsjfLayout.setVerticalGroup(
            panelsjfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelsjf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelsjf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel3.setText("Round Robin");

        jLabel4.setText("FIFO");

        jLabel5.setText("Shortest Job First");

        javax.swing.GroupLayout panelsemafororobinLayout = new javax.swing.GroupLayout(panelsemafororobin);
        panelsemafororobin.setLayout(panelsemafororobinLayout);
        panelsemafororobinLayout.setHorizontalGroup(
            panelsemafororobinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        panelsemafororobinLayout.setVerticalGroup(
            panelsemafororobinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 27, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelsemaforofifoLayout = new javax.swing.GroupLayout(panelsemaforofifo);
        panelsemaforofifo.setLayout(panelsemaforofifoLayout);
        panelsemaforofifoLayout.setHorizontalGroup(
            panelsemaforofifoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 27, Short.MAX_VALUE)
        );
        panelsemaforofifoLayout.setVerticalGroup(
            panelsemaforofifoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelsemaforosjfLayout = new javax.swing.GroupLayout(panelsemaforosjf);
        panelsemaforosjf.setLayout(panelsemaforosjfLayout);
        panelsemaforosjfLayout.setHorizontalGroup(
            panelsemaforosjfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 27, Short.MAX_VALUE)
        );
        panelsemaforosjfLayout.setVerticalGroup(
            panelsemaforosjfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel1)
                        .addGap(90, 90, 90)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel4)
                        .addGap(59, 59, 59)
                        .addComponent(panelsemaforofifo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(panelsemaforosjf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(panelRound, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(panelFIFO, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(panelsemafororobin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(118, 118, 118)
                                .addComponent(txtRafaga, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70)
                                .addComponent(txtLLegada, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(160, 160, 160)
                                .addComponent(cmbAlgoritmo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSimular)
                            .addComponent(btnIngresar))))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRafaga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLLegada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIngresar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimular)
                    .addComponent(cmbAlgoritmo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(panelsemafororobin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(panelRound, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(jLabel4))
                            .addComponent(panelsemaforofifo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelFIFO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5))
                    .addComponent(panelsemaforosjf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbAlgoritmoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAlgoritmoActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cmbAlgoritmoActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        // TODO add your handling code here:
        //System.out.println("HOLASSSSSSSSSSSSSS");
        
        String tipoAlg = this.cmbAlgoritmo.getSelectedItem().toString();
        System.out.println("TIPOALG" + tipoAlg);
        if (tipoAlg.equals("1. Round Robin")) {

            this.round.quantum = 4;
            String llegada = this.txtLLegada.getText();
            String rafaga = this.txtRafaga.getText();

            int l = 0;
            int r = (int) (Math.random() * 10 + 1);

            if (!llegada.isEmpty()) {
                l = Integer.parseInt(llegada);
            }
            if (!rafaga.isEmpty()) {
                r = Integer.parseInt(rafaga);
            }

            this.round.insertar(l, r);
            this.txtArearobin.setText(this.round.listar());

        } else if (tipoAlg.equals("2. FIFO")) {
            String llegada = this.txtLLegada.getText();
            String rafaga = this.txtRafaga.getText();

            int l = 0;
            int r = (int) (Math.random() * 10 + 1);

            if (!llegada.isEmpty()) {
                l = Integer.parseInt(llegada);
            }
            if (!rafaga.isEmpty()) {
                r = Integer.parseInt(rafaga);
            }

            this.fifo.insertar(l, r);
            this.txtAreafifo.setText(this.fifo.listar());
        } else if (tipoAlg.equals("3. SJF")) {
            String llegada = this.txtLLegada.getText();
            String rafaga = this.txtRafaga.getText();

            int l = 0;
            int r = (int) (Math.random() * 10 + 1);

            if (!llegada.isEmpty()) {
                l = Integer.parseInt(llegada);
            }
            if (!rafaga.isEmpty()) {
                r = Integer.parseInt(rafaga);
            }

            this.sjf.insertar(l, r);
            this.txtAreasjf.setText(this.sjf.listar());

            

        }
        
        if (ejecutando) {
                round.setAlert(tipoAlg);
                round.calcularRoundTiempos();
                this.txtArearobin.setText(round.listar());

                fifo.setAlert(tipoAlg);
                fifo.calcularTiempos();
                this.txtAreafifo.setText(fifo.listar());

                sjf.setAlert(tipoAlg);
                sjf.calcularTiemposSJF();
                this.txtAreasjf.setText(sjf.listar());
            }
    }//GEN-LAST:event_btnIngresarActionPerformed


    private void btnSimularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimularActionPerformed
        // TODO add your handling code here: btnejecutar
        ejecutando = true;
        //this.btnSimular.setVisible(false);
        round.calcularRoundTiempos();
        this.txtArearobin.setText(round.listar());

        fifo.calcularTiempos();
        this.txtAreafifo.setText(fifo.listar());

        sjf.calcularTiemposSJF();
        System.out.println("EL NUEVO SJF \n "+sjf.listar());
        //sjf.calcularTiempos();
        //sjf.tiempoFinal = sjf.ultimo.tfinal;
        
        this.txtAreasjf.setText(sjf.listar());

        this.btnSimular.setEnabled(false);
        round.start();
        fifo.start();
        sjf.start();
        this.btnSimular.setEnabled(true);
    }//GEN-LAST:event_btnSimularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnSimular;
    private javax.swing.JComboBox<String> cmbAlgoritmo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel panelFIFO;
    private javax.swing.JPanel panelRound;
    private javax.swing.JPanel panelfifo;
    private javax.swing.JPanel panelround;
    private javax.swing.JPanel panelsemaforofifo;
    private javax.swing.JPanel panelsemafororobin;
    private javax.swing.JPanel panelsemafororobin2;
    private javax.swing.JPanel panelsemaforosjf;
    private javax.swing.JPanel panelsjf;
    private javax.swing.JTextArea txtAreafifo;
    private javax.swing.JTextArea txtArearobin;
    private javax.swing.JTextArea txtAreasjf;
    private javax.swing.JTextField txtLLegada;
    private javax.swing.JTextField txtRafaga;
    // End of variables declaration//GEN-END:variables
}
