/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package multicolas;

/**
 *
 * @author luisy
 */
public class Frame extends javax.swing.JFrame {

    /**
     * Creates new form Frame
     */
    int semaforo = 0;

    boolean ejecutando = false;
    HiloMulticola round;
    HiloMulticola fifo;
    HiloMulticola sjf;

    public Frame(HiloMulticola round, HiloMulticola fifo, HiloMulticola sjf) {
        initComponents();
        //this.txtQuantum.setVisible(false);
        //this.jLabel3.setVisible(false);
        this.round = round;
        this.fifo = fifo;
        this.sjf = sjf;
        
        this.round.setPanel(this.panelgrafica, this.panelsemafororobin);
        this.fifo.setPanel(this.panelgrafica, this.panelsemafororobin);
        this.sjf.setPanel(this.panelgrafica, this.panelsemafororobin);
        
        this.round.setTextArea(this.txtArearobin);
        this.sjf.setTextArea(this.txtAreasjf);
        this.fifo.setTextArea(this.txtAreafifo);
        
    }

    private Frame() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelsemafororobin2 = new javax.swing.JPanel();
        txtRafaga = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtLLegada = new javax.swing.JTextField();
        cmbAlgoritmo = new javax.swing.JComboBox<>();
        btnIngresar = new javax.swing.JButton();
        btnSimular = new javax.swing.JButton();
        panelRound = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArearobin = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreafifo = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAreasjf = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        panelsemafororobin = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        panelgrafica = new javax.swing.JPanel();

        javax.swing.GroupLayout panelsemafororobin2Layout = new javax.swing.GroupLayout(panelsemafororobin2);
        panelsemafororobin2.setLayout(panelsemafororobin2Layout);
        panelsemafororobin2Layout.setHorizontalGroup(
            panelsemafororobin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 27, Short.MAX_VALUE)
        );
        panelsemafororobin2Layout.setVerticalGroup(
            panelsemafororobin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ráfaga");

        jLabel2.setText("Llegada");

        cmbAlgoritmo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1. Round Robin", "2. FIFO", "3. RoundRobin" }));
        cmbAlgoritmo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAlgoritmoActionPerformed(evt);
            }
        });

        btnIngresar.setLabel("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        btnSimular.setLabel("Simular");
        btnSimular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimularActionPerformed(evt);
            }
        });

        txtArearobin.setColumns(20);
        txtArearobin.setRows(5);
        jScrollPane1.setViewportView(txtArearobin);

        txtAreafifo.setColumns(20);
        txtAreafifo.setRows(5);
        jScrollPane2.setViewportView(txtAreafifo);

        txtAreasjf.setColumns(20);
        txtAreasjf.setRows(5);
        jScrollPane3.setViewportView(txtAreasjf);

        javax.swing.GroupLayout panelRoundLayout = new javax.swing.GroupLayout(panelRound);
        panelRound.setLayout(panelRoundLayout);
        panelRoundLayout.setHorizontalGroup(
            panelRoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRoundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRoundLayout.setVerticalGroup(
            panelRoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRoundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel3.setText("Round Robin");

        jLabel4.setText("FIFO");

        javax.swing.GroupLayout panelsemafororobinLayout = new javax.swing.GroupLayout(panelsemafororobin);
        panelsemafororobin.setLayout(panelsemafororobinLayout);
        panelsemafororobinLayout.setHorizontalGroup(
            panelsemafororobinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        panelsemafororobinLayout.setVerticalGroup(
            panelsemafororobinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 27, Short.MAX_VALUE)
        );

        jLabel5.setText("RoundRobin2");

        panelgrafica.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout panelgraficaLayout = new javax.swing.GroupLayout(panelgrafica);
        panelgrafica.setLayout(panelgraficaLayout);
        panelgraficaLayout.setHorizontalGroup(
            panelgraficaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelgraficaLayout.setVerticalGroup(
            panelgraficaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 404, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelsemafororobin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(359, 359, 359)
                        .addComponent(jLabel5)
                        .addGap(303, 303, 303))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelRound, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelgrafica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addComponent(jLabel1)
                                .addGap(90, 90, 90)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(118, 118, 118)
                                        .addComponent(txtRafaga, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(70, 70, 70)
                                        .addComponent(txtLLegada, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(160, 160, 160)
                                        .addComponent(cmbAlgoritmo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(78, 78, 78)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSimular)
                                    .addComponent(btnIngresar))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRafaga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLLegada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIngresar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimular)
                    .addComponent(cmbAlgoritmo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelsemafororobin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)))
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelRound, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(panelgrafica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbAlgoritmoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAlgoritmoActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cmbAlgoritmoActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        // TODO add your handling code here:
        //System.out.println("HOLASSSSSSSSSSSSSS");
        
        String tipoAlg = this.cmbAlgoritmo.getSelectedItem().toString();
        System.out.println("TIPOALG" + tipoAlg);
        if (tipoAlg.equals("1. Round Robin")) {

            this.round.quantum = 4;
            String llegada = this.txtLLegada.getText();
            String rafaga = this.txtRafaga.getText();

            int l = 0;
            int r = (int) (Math.random() * 10 + 1);

            if (!llegada.isEmpty()) {
                l = Integer.parseInt(llegada);
            }
            if (!rafaga.isEmpty()) {
                r = Integer.parseInt(rafaga);
            }

            this.round.insertar(l, r);
            this.txtArearobin.setText(this.round.listar());

        } else if (tipoAlg.equals("2. FIFO")) {
            String llegada = this.txtLLegada.getText();
            String rafaga = this.txtRafaga.getText();

            int l = 0;
            int r = (int) (Math.random() * 10 + 1);

            if (!llegada.isEmpty()) {
                l = Integer.parseInt(llegada);
            }
            if (!rafaga.isEmpty()) {
                r = Integer.parseInt(rafaga);
            }

            this.fifo.insertar(l, r);
            this.txtAreafifo.setText(this.fifo.listar());
        } else if (tipoAlg.equals("3. RoundRobin")) {
            
            this.sjf.quantum = 4;
            String llegada = this.txtLLegada.getText();
            String rafaga = this.txtRafaga.getText();

            int l = 0;
            int r = (int) (Math.random() * 10 + 1);

            if (!llegada.isEmpty()) {
                l = Integer.parseInt(llegada);
            }
            if (!rafaga.isEmpty()) {
                r = Integer.parseInt(rafaga);
            }

            this.sjf.insertar(l, r);
            this.txtAreasjf.setText(this.sjf.listar());

            

        }
        
        if (ejecutando) {
                round.setAlert(tipoAlg);
                round.calcularRoundTiempos();
                this.txtArearobin.setText(round.listar());

                fifo.setAlert(tipoAlg);
                fifo.calcularTiempos();
                this.txtAreafifo.setText(fifo.listar());

                sjf.setAlert(tipoAlg);
                sjf.calcularTiemposSJF();
                this.txtAreasjf.setText(sjf.listar());
            }
    }//GEN-LAST:event_btnIngresarActionPerformed


    private void btnSimularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimularActionPerformed
        // TODO add your handling code here: btnejecutar
        ejecutando = true;
        //this.btnSimular.setVisible(false);
        round.calcularRoundTiempos();
        this.txtArearobin.setText(round.listar());
        System.out.println("EJECUTE ROUNDROBIN");
        
        fifo.calcularTiempos();
        this.txtAreafifo.setText(fifo.listar());
        System.out.println("EJECUTÉÉ FIFOO");    
        
        sjf.calcularTiemposSJF();
        //System.out.println("EL NUEVO SJF \n "+sjf.listar());
        //sjf.calcularTiempos();
        //sjf.tiempoFinal = sjf.ultimo.tfinal;
        
        this.txtAreasjf.setText(sjf.listar());
        System.out.println("EJECUTÉÉ SJF");
        
        
        this.btnSimular.setEnabled(false);
        round.start();
        //fifo.start();
        //sjf.start();
        this.btnSimular.setEnabled(true);
    }//GEN-LAST:event_btnSimularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnSimular;
    private javax.swing.JComboBox<String> cmbAlgoritmo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel panelRound;
    private javax.swing.JPanel panelgrafica;
    private javax.swing.JPanel panelsemafororobin;
    private javax.swing.JPanel panelsemafororobin2;
    private javax.swing.JTextArea txtAreafifo;
    private javax.swing.JTextArea txtArearobin;
    private javax.swing.JTextArea txtAreasjf;
    private javax.swing.JTextField txtLLegada;
    private javax.swing.JTextField txtRafaga;
    // End of variables declaration//GEN-END:variables
}
